/**
 * This file is autogenerated by the event-sync plugin.
 * See stencil.config.ts in the root directory.
 */
export default {
  didDismiss: 'lyne-toast_did-dismiss',
  didPresent: 'lyne-toast_did-present',
  willDismiss: 'lyne-toast_will-dismiss',
  willPresent: 'lyne-toast_will-present'
};
