/**
 * Docs: https://github.com/open-wc/custom-elements-manifest/tree/master/packages/to-markdown
 */
import { existsSync, globSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

import { customElementsManifestToMarkdown } from '@custom-elements-manifest/to-markdown';
import type { Attribute, ClassDeclaration, CustomElement, Package } from 'custom-elements-manifest';
// eslint-disable-next-line @typescript-eslint/naming-convention
import MagicString from 'magic-string';
import { format, resolveConfig } from 'prettier';

import elementsManifestConfig from '../manifest/elements-custom-elements-manifest.config.ts';
import elementsExperimentalManifestConfig from '../manifest/elements-experimental-custom-elements-manifest.config.ts';

const projectRoot = fileURLToPath(new URL('../../', import.meta.url));
const manifestFilePaths = [
  `${elementsManifestConfig.outdir}/custom-elements.json`,
  `${elementsExperimentalManifestConfig.outdir}/custom-elements.json`,
];
const tempFolderPath = join(projectRoot, 'dist/docs');
const inheritedFromColumnIndex = 6;
const propertyColumnIndex = 1;
const attributeColumnIndex = 2;
const autoGeneratedMarker = '<!-- Auto Generated Below -->';

function getAttributeName(propertyName: string, attributes: Attribute[]): string {
  const name = propertyName.replace(/['`]/g, '').trim();
  const attr = attributes.find((a) => a.fieldName === name)?.name;
  return attr ? `\`${attr}\`` : '-';
}

/**
 * Add the 'attribute' column.
 * Removes the 'Inherited from' column.
 * Replace 'Fields' title with 'Properties'
 */
function updateFieldsTable(
  newDocs: MagicString,
  sections: RegExpMatchArray[],
  attributes?: Attribute[],
): void {
  const fieldsSectionIndex = sections.findIndex((sect) => sect.groups!.name === 'Fields');
  const startIndex = sections[fieldsSectionIndex]?.index;
  const endIndex = sections[fieldsSectionIndex + 1]?.index;
  if (fieldsSectionIndex === -1) {
    return;
  }

  // Create a matrix 'table[row][column]' structure for the fields table
  const fieldsSection = newDocs.original
    .substring(startIndex!, endIndex)
    // Remove leading pipes (prettier artifacts in ts files)
    .replaceAll('`\\| ', '`')
    // Remove doubled spaces (unwanted artifacts)
    .replace(/  +/g, ' ');

  const tableRows = Array.from(fieldsSection.matchAll(/^\|.*\|$/gm))
    .map((match) => match[0])
    .map((row) => row.split(/(?<!\\)\|/g)); // Split by not escaped '|'

  // Remove the 'Inherited from' column
  tableRows.forEach((row) => row.splice(inheritedFromColumnIndex, 1));

  // Add the 'attribute' column using the attributes collection (read from the manifest)
  const attributeColumn = [
    tableRows[0][propertyColumnIndex].replace('Name', 'Attribute').trim(),
    tableRows[1][propertyColumnIndex],
    ...tableRows
      .slice(2)
      .map((entry) => getAttributeName(entry[propertyColumnIndex], attributes || [])),
  ];

  // Insert the attribute column in the table
  attributeColumn.forEach((attributeColumn, i) =>
    tableRows[i].splice(attributeColumnIndex, 0, attributeColumn),
  );

  const fieldsTable = tableRows.map((cols) => cols.join('|')).join('\n');
  newDocs.update(
    startIndex!,
    endIndex ?? newDocs.original.length,
    `#### Properties\n\n${fieldsTable}\n\n`,
  );
}

function generateDocsForClass(docs: string, manifest: CustomElement): string {
  let newDocs = new MagicString(docs);

  // Remove the details (private API) section and commit the change
  const detailsSectionStart = newDocs.original.match(/<details>/)?.index;
  newDocs.remove(detailsSectionStart!, newDocs.original.length);
  newDocs = new MagicString(newDocs.toString());

  const sections = Array.from(newDocs.original.matchAll(/[#]+ (?<name>.+)/g));

  updateFieldsTable(newDocs, sections, manifest.attributes ?? []);
  newDocs = new MagicString(newDocs.toString());

  // Unescape `
  newDocs.replace(/\\`/g, '`');

  // Unescape tag openings
  newDocs.replace(/\\</g, '<');

  // Unescape : (Fixes URL)
  newDocs.replace(/\\:/g, ':');

  // Replace &#xA; with space
  newDocs.replace(/&#xA;/g, ' ');

  return newDocs.toString();
}

type ExtendedClassDeclaration = ClassDeclaration & {
  cssProperties: { name: string }[];
  events: { name: string }[];
  members: { name: string }[];
  slots: { name: string }[];
};

for (const manifestPath of manifestFilePaths) {
  const manifest: Package = JSON.parse(readFileSync(manifestPath, 'utf-8'));

  manifest.modules.forEach((module) => {
    module.declarations
      ?.filter(
        (declaration): declaration is ExtendedClassDeclaration => declaration.kind === 'class',
      )
      .forEach((declaration) => {
        ['members', 'slots', 'cssProperties', 'events', 'cssParts'].forEach((type) =>
          (declaration[type as keyof ExtendedClassDeclaration] as { name: string }[])?.sort(
            (a, b) => (a.name ?? '').localeCompare(b.name ?? ''),
          ),
        );
        declaration.members?.forEach((member) => {
          if (member.deprecated) {
            member.description += '<br><strong>Deprecated</strong>';
            if (typeof member.deprecated === 'string') {
              member.description += `: ${member.deprecated}`;
            }
          }
        });
      });
  });

  const markdown: string = customElementsManifestToMarkdown(manifest, {
    headingOffset: 1,
    private: 'details', // We use 'details' because it's the only way to remove 'protected' members from the tables. We remove details section later.
    omitDeclarations: ['exports'],
    omitSections: ['super-class', 'main-heading', 'static-fields', 'attributes', 'mixins'],
  });
  const manifestDeclarations = manifest.modules.flatMap((m) => m.declarations);

  mkdirSync(tempFolderPath, { recursive: true });
  writeFileSync(`${tempFolderPath}/components.md`, markdown);

  // Split the generated file into the single readme of each component
  const matches = Array.from(markdown.matchAll(/^[#]+ class: `(?<name>.*)`, `(?<tag>.*)`$/gm));

  const classDocs = new Map<string, string>();
  for (let i = 0; i < matches.length; i++) {
    const startIndex = matches[i].index!;
    const endIndex = matches[i + 1]?.index ?? markdown.length;
    const compName = matches[i].groups!.name;

    const componentMarkdown = markdown.substring(startIndex, endIndex);

    // If there is a `<hr/>` it indicates corrupted data respect. mixed data over different components.
    // If we just stop before occurrence of `<hr/>` we are not including the corrupted data.
    const hrIndex = componentMarkdown.indexOf('<hr/>');
    const markdownDoc = componentMarkdown.substring(0, hrIndex);
    const compManifest = manifestDeclarations.find(
      (c) => c?.kind === 'class' && c.name === compName,
    ) as CustomElement;

    classDocs.set(compName, generateDocsForClass(markdownDoc, compManifest));
  }

  const packageName = basename(dirname(manifestPath));
  const readmes = globSync(join(projectRoot, 'src', packageName, '**', 'readme.md'));
  for (const readme of readmes) {
    const moduleName = basename(dirname(readme));
    if (!existsSync(join(dirname(dirname(readme)), `${moduleName}.pure.ts`))) {
      console.warn(
        `Unexpected ${relative(projectRoot, readme)} in ${relative(projectRoot, fileURLToPath(import.meta.url))}. Please adapt logic.`,
      );
      continue;
    }

    const content = readFileSync(readme, 'utf8').split(autoGeneratedMarker)[0];
    let docs = manifest.modules
      .filter((m) => m.path.startsWith(moduleName + '/'))
      .flatMap((m) => m.declarations)
      .filter((d) => d?.kind === 'class')
      .map((d) => d.name)
      .sort()
      .map((n) => classDocs.get(n))
      .filter((d) => !!d)
      .join('\n\n')
      .trim();
    if (docs) {
      docs = `## API Documentation\n\n${docs}`;
    }

    const newReadme = `${content.trim()}\n\n${autoGeneratedMarker}\n\n${docs}`;
    const options = await resolveConfig(readme);
    writeFileSync(readme, await format(newReadme, { ...options, filepath: readme }), 'utf8');
  }

  console.log(`Docs generated successfully from ${manifestPath}`);
}
