/**
 * This file is autogenerated by the event-sync plugin.
 * See stencil.config.ts in the root directory.
 */
export default {
  optionClick: 'option-click',
  selectionChange: 'option-selection-change',
};
