/**
 * This file is autogenerated by the event-sync plugin.
 * See stencil.config.ts in the root directory.
 */
export default {
  optionSelected: 'option-selected',
  selectionChange: 'option-selection-change',
};
