/**
 * This file is autogenerated by the event-sync plugin.
 * See stencil.config.ts in the root directory.
 */
export default {
  sbbRadioButtonLoaded: 'sbb-radio-button-loaded',
  stateChange: 'state-change',
};
