/**
 * This file is autogenerated by the event-sync plugin.
 * See stencil.config.ts in the root directory.
 */
export default {
  didDismiss: 'lyne-alert_did-dismiss',
  didPresent: 'lyne-alert_did-present',
  willPresent: 'lyne-alert_will-present'
};
