import type { SeatReservation } from '../../types.ts';

export const MOCK_DB_WALLS_TRAIN: SeatReservation = {
  vehicleType: 'TRAIN',
  deckCoachIndex: 0,
  deckCoachLevel: 'SINGLE_DECK',
  coachItems: [
    {
      id: '21',
      number: 'coach information missing',
      dimension: {
        w: 58000,
        h: 10000,
      },
      places: [
        {
          number: '15',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 0,
            y: 0,
            z: 0,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },

        {
          number: '11',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 0,
            y: 8000,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '16',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 2000,
            y: 0,
            z: 0,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '12',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 2000,
            y: 8000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '25',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 4000,
            y: 0,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '21',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 4000,
            y: 8000,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '26',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 8000,
            y: 0,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '28',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 8000,
            y: 2000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '24',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 8000,
            y: 6000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '22',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 8000,
            y: 8000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '35',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 10000,
            y: 0,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '37',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 10000,
            y: 2000,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '33',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 10000,
            y: 6000,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '31',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 10000,
            y: 8000,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '36',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 12000,
            y: 0,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '38',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 12000,
            y: 2000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '34',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 12000,
            y: 6000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '32',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 12000,
            y: 8000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '43',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 14000,
            y: 6000,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '41',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 14000,
            y: 8000,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '46',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 16000,
            y: 0,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '48',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 16000,
            y: 2000,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '44',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 16000,
            y: 6000,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '42',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 16000,
            y: 8000,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '55',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 18000,
            y: 0,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '57',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 18000,
            y: 2000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '53',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 18000,
            y: 6000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '51',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 18000,
            y: 8000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '65',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 20000,
            y: 0,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '67',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 20000,
            y: 2000,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '63',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 20000,
            y: 6000,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '61',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 20000,
            y: 8000,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '66',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 24000,
            y: 0,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '68',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 24000,
            y: 2000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '64',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 24000,
            y: 6000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '62',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 24000,
            y: 8000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '75',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 26000,
            y: 0,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '77',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 26000,
            y: 2000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '76',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 28000,
            y: 0,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '78',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 28000,
            y: 2000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '85',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 30000,
            y: 0,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '83',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 30000,
            y: 2000,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '81',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 30000,
            y: 4000,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '86',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 34000,
            y: 0,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '84',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 34000,
            y: 2000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '82',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 34000,
            y: 4000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '95',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 36000,
            y: 0,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '93',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 36000,
            y: 2000,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '91',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 36000,
            y: 4000,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '96',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 40000,
            y: 0,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '94',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 40000,
            y: 2000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '92',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 40000,
            y: 4000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '105',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 42000,
            y: 0,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '103',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 42000,
            y: 2000,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '101',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 42000,
            y: 4000,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '106',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 46000,
            y: 0,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '104',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 46000,
            y: 2000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '102',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 46000,
            y: 4000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '115',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 48000,
            y: 0,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '113',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 48000,
            y: 2000,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '111',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 48000,
            y: 4000,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '116',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 52000,
            y: 0,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '114',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 52000,
            y: 2000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '112',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 52000,
            y: 4000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
      ],
      serviceElements: [
        {
          icon: 'MOBILE_PHONE_ICON',
          position: {
            x: 14000,
            y: 4000,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 2000,
          },
        },
        {
          icon: 'SILENCE_ICON',
          position: {
            x: 40000,
            y: 6000,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 2000,
          },
        },
        {
          icon: 'MOBILE_PHONE_FORBIDDEN_ICON',
          position: {
            x: 42000,
            y: 6000,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 2000,
          },
        },
      ],
      graphicElements: [
        {
          icon: 'TABLE',
          position: {
            x: 6000,
            y: 0,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 4000,
          },
          rotation: 0,
        },
        {
          icon: 'TABLE',
          position: {
            x: 6000,
            y: 6000,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 4000,
          },
          rotation: 180,
        },
        {
          icon: 'TABLE',
          position: {
            x: 22000,
            y: 0,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 4000,
          },
          rotation: 0,
        },
        {
          icon: 'TABLE',
          position: {
            x: 22000,
            y: 6000,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 4000,
          },
          rotation: 180,
        },
        {
          icon: 'T_WALL_COMPARTMENTS_1',
          position: {
            x: 3000,
            y: 8000,
            z: 0,
          },
          dimension: {
            w: 2000,
            h: 2000,
          },
          rotation: 180,
        },
        {
          icon: 'T_WALL_COMPARTMENTS_2',
          position: {
            x: 9000,
            y: 6000,
            z: 0,
          },
          dimension: {
            w: 2000,
            h: 4000,
          },
          rotation: 180,
        },
        {
          icon: 'WALL_LEFT_1',
          position: {
            x: 2000,
            y: 0,
            z: 0,
          },
          dimension: {
            w: 2000,
            h: 2000,
          },
          rotation: 0,
        },

        {
          icon: 'WALL_LEFT_2',
          position: {
            x: 12000,
            y: 0,
            z: 0,
          },
          dimension: {
            w: 2000,
            h: 4000,
          },
          rotation: 0,
        },
        {
          icon: 'WALL_LEFT_2',
          position: {
            x: 18000,
            y: 0,
            z: 0,
          },
          dimension: {
            w: 2000,
            h: 4000,
          },
          rotation: 0,
        },
        {
          icon: 'T_WALL_COMPARTMENTS_2',
          position: {
            x: 9000,
            y: 0,
            z: 0,
          },
          dimension: {
            w: 2000,
            h: 4000,
          },
          rotation: 0,
        },
        {
          icon: 'WALL_RIGHT_2',
          position: {
            x: 16000,
            y: 0,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 4000,
          },
          rotation: 0,
        },
        {
          icon: 'WALL_RIGHT_2',
          position: {
            x: 12000,
            y: 6000,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 4000,
          },
          rotation: 180,
        },
        {
          icon: 'WALL_RIGHT_2',
          position: {
            x: 18000,
            y: 6000,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 4000,
          },
          rotation: 180,
        },
        {
          icon: 'WALL_LEFT_2',
          position: {
            x: 16000,
            y: 6000,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 4000,
          },
          rotation: 180,
        },
        {
          icon: 'WALL_RIGHT_3',
          position: {
            x: 30000,
            y: 0,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 6000,
          },
          rotation: 0,
        },
        {
          icon: 'TABLE',
          position: {
            x: 32000,
            y: 0,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 2000,
          },
          rotation: 0,
        },
        {
          icon: 'T_WALL_COMPARTMENTS_3',
          position: {
            x: 35000,
            y: 0,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 6000,
          },
          rotation: 0,
        },
        {
          icon: 'TABLE',
          position: {
            x: 38000,
            y: 0,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 2000,
          },
          rotation: 0,
        },
        {
          icon: 'T_WALL_COMPARTMENTS_3',
          position: {
            x: 41000,
            y: 0,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 6000,
          },
          rotation: 0,
        },
        {
          icon: 'TABLE',
          position: {
            x: 44000,
            y: 0,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 2000,
          },
          rotation: 0,
        },
        {
          icon: 'T_WALL_COMPARTMENTS_3',
          position: {
            x: 47000,
            y: 0,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 6000,
          },
          rotation: 0,
        },
        {
          icon: 'TABLE',
          position: {
            x: 50000,
            y: 0,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 2000,
          },
          rotation: 0,
        },
        {
          icon: 'WALL_LEFT_3',
          position: {
            x: 52000,
            y: 0,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 6000,
          },
          rotation: 0,
        },
        {
          icon: 'LUGGAGE_AREA',
          position: {
            x: 14000,
            y: 0,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 2000,
          },
          rotation: 0,
        },
        {
          icon: 'LUGGAGE_AREA',
          position: {
            x: 26000,
            y: 8000,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 2000,
          },
          rotation: 0,
        },
        {
          icon: 'TOILET_AREA',
          position: {
            x: 54000,
            y: 0,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 2000,
          },
          rotation: 0,
        },
        {
          icon: 'TOILET_AREA',
          position: {
            x: 56000,
            y: 0,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 2000,
          },
          rotation: 0,
        },
        {
          icon: 'COACH_WALL_NO_PASSAGE',
          position: {
            x: 0,
            y: 0,
            z: 0,
          },
          dimension: {
            w: 1000,
            h: 10000,
          },
          rotation: 0,
        },
        {
          icon: 'COACH_WALL_NO_PASSAGE',
          position: {
            x: 57000,
            y: 0,
            z: 0,
          },
          dimension: {
            w: 1000,
            h: 10000,
          },
          rotation: 180,
        },
      ],
      travelClass: ['SECOND'],
      propertyIds: ['SEAT', 'MOBILE_PHONE_ICON'],
    },
    {
      id: '22',
      number: 'coach all partition walls',
      dimension: {
        w: 58000,
        h: 10000,
      },
      places: [
        {
          number: '211',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 1000,
            y: 0,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '212',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 1000,
            y: 2000,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '213',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 1000,
            y: 4000,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '214',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 1000,
            y: 8000,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '221',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 5000,
            y: 0,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '222',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 5000,
            y: 2000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '223',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 5000,
            y: 4000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '224',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 5000,
            y: 8000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '231',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 7000,
            y: 0,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '232',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 7000,
            y: 2000,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '233',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 7000,
            y: 4000,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '234',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 7000,
            y: 8000,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '241',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 11000,
            y: 0,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '242',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 11000,
            y: 2000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '243',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 11000,
            y: 4000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '244',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 11000,
            y: 8000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '251',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 13000,
            y: 0,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '252',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 13000,
            y: 2000,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '253',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 13000,
            y: 4000,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '254',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 13000,
            y: 8000,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '261',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 17000,
            y: 0,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '262',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 17000,
            y: 2000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '263',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 17000,
            y: 4000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '264',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 17000,
            y: 8000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '271',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 19000,
            y: 0,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '272',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 19000,
            y: 2000,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '274',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 19000,
            y: 8000,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '281',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 23000,
            y: 0,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '282',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 23000,
            y: 2000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '283',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 23000,
            y: 6000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '284',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 23000,
            y: 8000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '291',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 25000,
            y: 0,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '292',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 25000,
            y: 2000,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '293',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 25000,
            y: 6000,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '294',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 25000,
            y: 8000,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '301',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 29000,
            y: 0,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '302',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 29000,
            y: 2000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '303',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 29000,
            y: 6000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '304',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 29000,
            y: 8000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '311',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 31000,
            y: 0,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '312',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 31000,
            y: 2000,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '313',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 31000,
            y: 6000,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '314',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 31000,
            y: 8000,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '321',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 35000,
            y: 0,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '322',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 35000,
            y: 2000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '323',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 35000,
            y: 6000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '324',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 35000,
            y: 8000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '342',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 41000,
            y: 4000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '343',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 41000,
            y: 6000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '344',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 41000,
            y: 8000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '351',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 43000,
            y: 0,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '352',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 43000,
            y: 4000,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '353',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 43000,
            y: 6000,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '354',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 43000,
            y: 8000,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '361',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 47000,
            y: 0,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '362',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 47000,
            y: 4000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '363',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 47000,
            y: 6000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '364',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 47000,
            y: 8000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '371',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 49000,
            y: 0,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '372',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 49000,
            y: 4000,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '373',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 49000,
            y: 6000,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '374',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 49000,
            y: 8000,
            z: 1,
          },
          rotation: 0,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '381',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 53000,
            y: 0,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '382',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 53000,
            y: 4000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '383',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 53000,
            y: 6000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
        {
          number: '384',
          state: 'FREE',
          type: 'SEAT',
          dimension: {
            w: 2000,
            h: 2000,
          },
          position: {
            x: 53000,
            y: 8000,
            z: 1,
          },
          rotation: 180,
          travelClass: 'SECOND',
          propertyIds: [],
        },
      ],
      serviceElements: [
        {
          icon: 'SILENCE_ICON',
          position: {
            x: 19000,
            y: 4000,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 2000,
          },
        },
        {
          icon: 'MOBILE_PHONE_ICON',
          position: {
            x: 37000,
            y: 2000,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 2000,
          },
        },
      ],
      graphicElements: [
        {
          icon: 'TABLE',
          position: {
            x: 3000,
            y: 0,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 2000,
          },
          rotation: 0,
        },
        {
          icon: 'TABLE',
          position: {
            x: 3000,
            y: 8000,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 2000,
          },
          rotation: 180,
        },
        {
          icon: 'TABLE',
          position: {
            x: 9000,
            y: 0,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 2000,
          },
          rotation: 0,
        },
        {
          icon: 'TABLE',
          position: {
            x: 9000,
            y: 8000,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 2000,
          },
          rotation: 180,
        },
        {
          icon: 'TABLE',
          position: {
            x: 15000,
            y: 0,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 2000,
          },
          rotation: 0,
        },
        {
          icon: 'TABLE',
          position: {
            x: 15000,
            y: 8000,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 2000,
          },
          rotation: 180,
        },
        {
          icon: 'WALL_RIGHT_3',
          position: {
            x: 1000,
            y: 0,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 6000,
          },
          rotation: 0,
        },
        {
          icon: 'T_WALL_COMPARTMENTS_3',
          position: {
            x: 6000,
            y: 0,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 6000,
          },
          rotation: 0,
        },
        {
          icon: 'WALL_COMPARTMENTS_3',
          position: {
            x: 12000,
            y: 0,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 6000,
          },
          rotation: 0,
        },
        {
          icon: 'WALL_LEFT_3',
          position: {
            x: 17000,
            y: 0,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 6000,
          },
          rotation: 0,
        },
        {
          icon: 'WALL_LEFT_1',
          position: {
            x: 1000,
            y: 8000,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 2000,
          },
          rotation: 180,
        },
        {
          icon: 'T_WALL_COMPARTMENTS_1',
          position: {
            x: 6000,
            y: 8000,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 2000,
          },
          rotation: 180,
        },
        {
          icon: 'WALL_COMPARTMENTS_1',
          position: {
            x: 12000,
            y: 8000,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 2000,
          },
          rotation: 180,
        },
        {
          icon: 'WALL_RIGHT_1',
          position: {
            x: 17000,
            y: 8000,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 2000,
          },
          rotation: 180,
        },
        {
          icon: 'TABLE',
          position: {
            x: 21000,
            y: 0,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 2000,
          },
          rotation: 0,
        },
        {
          icon: 'TABLE',
          position: {
            x: 21000,
            y: 8000,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 2000,
          },
          rotation: 180,
        },
        {
          icon: 'TABLE',
          position: {
            x: 27000,
            y: 0,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 2000,
          },
          rotation: 0,
        },
        {
          icon: 'TABLE',
          position: {
            x: 27000,
            y: 8000,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 2000,
          },
          rotation: 180,
        },
        {
          icon: 'TABLE',
          position: {
            x: 33000,
            y: 0,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 2000,
          },
          rotation: 0,
        },
        {
          icon: 'TABLE',
          position: {
            x: 33000,
            y: 8000,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 2000,
          },
          rotation: 180,
        },
        {
          icon: 'T_WALL_COMPARTMENTS_2',
          position: {
            x: 24000,
            y: 0,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 4000,
          },
          rotation: 0,
        },
        {
          icon: 'WALL_COMPARTMENTS_2',
          position: {
            x: 30000,
            y: 0,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 4000,
          },
          rotation: 0,
        },
        {
          icon: 'WALL_LEFT_2',
          position: {
            x: 35000,
            y: 0,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 4000,
          },
          rotation: 0,
        },
        {
          icon: 'T_WALL_COMPARTMENTS_2',
          position: {
            x: 24000,
            y: 6000,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 4000,
          },
          rotation: 180,
        },
        {
          icon: 'WALL_COMPARTMENTS_2',
          position: {
            x: 30000,
            y: 6000,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 4000,
          },
          rotation: 180,
        },
        {
          icon: 'WALL_RIGHT_2',
          position: {
            x: 35000,
            y: 6000,
            z: 0,
          },
          dimension: {
            w: 2000,
            h: 4000,
          },
          rotation: 180,
        },
        {
          icon: 'TABLE',
          position: {
            x: 39000,
            y: 0,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 2000,
          },
          rotation: 0,
        },
        {
          icon: 'TABLE',
          position: {
            x: 39000,
            y: 8000,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 2000,
          },
          rotation: 180,
        },
        {
          icon: 'TABLE',
          position: {
            x: 45000,
            y: 0,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 2000,
          },
          rotation: 0,
        },
        {
          icon: 'TABLE',
          position: {
            x: 45000,
            y: 8000,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 2000,
          },
          rotation: 180,
        },
        {
          icon: 'TABLE',
          position: {
            x: 51000,
            y: 0,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 2000,
          },
          rotation: 0,
        },
        {
          icon: 'TABLE',
          position: {
            x: 51000,
            y: 8000,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 2000,
          },
          rotation: 180,
        },
        {
          icon: 'T_WALL_COMPARTMENTS_3',
          position: {
            x: 42000,
            y: 4000,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 6000,
          },
          rotation: 180,
        },
        {
          icon: 'WALL_COMPARTMENTS_3',
          position: {
            x: 48000,
            y: 4000,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 6000,
          },
          rotation: 180,
        },
        {
          icon: 'WALL_RIGHT_3',
          position: {
            x: 53000,
            y: 4000,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 6000,
          },
          rotation: 180,
        },
        {
          icon: 'TOILET_AREA',
          position: {
            x: 55000,
            y: 0,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 2000,
          },
          rotation: 0,
        },
        {
          icon: 'LUGGAGE_AREA',
          position: {
            x: 55000,
            y: 8000,
            z: 2,
          },
          dimension: {
            w: 2000,
            h: 2000,
          },
          rotation: 0,
        },
        {
          icon: 'COACH_WALL_NO_PASSAGE',
          position: {
            x: 0,
            y: 0,
            z: 0,
          },
          dimension: {
            w: 1000,
            h: 10000,
          },
          rotation: 0,
        },
        {
          icon: 'COACH_WALL_NO_PASSAGE',
          position: {
            x: 57000,
            y: 0,
            z: 0,
          },
          dimension: {
            w: 1000,
            h: 10000,
          },
          rotation: 180,
        },
      ],
      travelClass: ['SECOND'],
      propertyIds: ['SEAT', 'SILENCE_ICON'],
    },
  ],
};
