export const MOCK_TRAIN_LOCOMOTIVE_LAYOUT = {
  vehicleType: 'TRAIN',
  deckCoachIndex: 0,
  coachItems: [
    {
      id: '11',
      number: 'At2(501)',
      dimension: {
        w: 56,
        h: 10,
      },
      places: [],
      serviceElements: [],
      graphicElements: [
        {
          icon: 'DRIVER_AREA_NO_VERTICAL_WALL',
          dimension: {
            w: 6,
            h: 10,
          },
          position: {
            x: 0,
            y: 0,
            z: 0,
          },
          rotation: 0,
        },
        {
          icon: 'DRIVER_AREA_NO_VERTICAL_WALL',
          dimension: {
            w: 6,
            h: 10,
          },
          position: {
            x: 50,
            y: 0,
            z: 0,
          },
          rotation: 180,
        },
      ],
      travelClass: ['FIRST'],
      propertyIds: [],
      type: 'LOCOMOTIVE_COACH'
    },
    {
      id: '10',
      number: 'A3(501)',
      dimension: {
        w: 57,
        h: 10,
      },
      places: [
        {
          number: '66',
          state: 'ALLOCATED',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 180,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 48,
            y: 0,
            z: 0,
          },
        },
        {
          number: '56',
          state: 'ALLOCATED',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 180,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 45,
            y: 0,
            z: 0,
          },
        },
        {
          number: '55',
          state: 'ALLOCATED',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 0,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 41,
            y: 0,
            z: 0,
          },
        },
        {
          number: '54',
          state: 'ALLOCATED',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 180,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 45,
            y: 2,
            z: 0,
          },
        },
        {
          number: '53',
          state: 'ALLOCATED',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 0,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 41,
            y: 2,
            z: 0,
          },
        },
        {
          number: '35',
          state: 'ALLOCATED',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: ['TABLE'],
          selected: false,
          rotation: 0,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 19,
            y: 0,
            z: 0,
          },
        },
        {
          number: '33',
          state: 'ALLOCATED',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: ['TABLE'],
          selected: false,
          rotation: 0,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 19,
            y: 2,
            z: 0,
          },
        },
        {
          number: '34',
          state: 'ALLOCATED',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: ['TABLE'],
          selected: false,
          rotation: 180,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 24,
            y: 2,
            z: 0,
          },
        },
        {
          number: '36',
          state: 'ALLOCATED',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: ['TABLE'],
          selected: false,
          rotation: 180,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 24,
            y: 0,
            z: 0,
          },
        },
        {
          number: '46',
          state: 'ALLOCATED',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: ['TABLE'],
          selected: false,
          rotation: 180,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 31,
            y: 0,
            z: 0,
          },
        },
        {
          number: '45',
          state: 'ALLOCATED',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: ['TABLE'],
          selected: false,
          rotation: 0,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 26,
            y: 0,
            z: 0,
          },
        },
        {
          number: '44',
          state: 'ALLOCATED',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: ['TABLE'],
          selected: false,
          rotation: 180,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 31,
            y: 2,
            z: 0,
          },
        },
        {
          number: '43',
          state: 'ALLOCATED',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: ['TABLE'],
          selected: false,
          rotation: 0,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 26,
            y: 2,
            z: 0,
          },
        },
        {
          number: '41',
          state: 'ALLOCATED',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: ['TABLE'],
          selected: false,
          rotation: 0,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 26,
            y: 8,
            z: 0,
          },
        },
        {
          number: '42',
          state: 'ALLOCATED',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: ['TABLE'],
          selected: false,
          rotation: 180,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 31,
            y: 8,
            z: 0,
          },
        },
        {
          number: '11',
          state: 'ALLOCATED',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 0,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 9,
            y: 8,
            z: 0,
          },
        },
        {
          number: '62',
          state: 'ALLOCATED',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 180,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 48,
            y: 8,
            z: 0,
          },
        },
        {
          number: '25',
          state: 'ALLOCATED',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: ['TABLE'],
          selected: false,
          rotation: 0,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 11,
            y: 0,
            z: 0,
          },
        },
        {
          number: '26',
          state: 'ALLOCATED',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: ['TABLE'],
          selected: false,
          rotation: 180,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 16,
            y: 0,
            z: 0,
          },
        },
        {
          number: '23',
          state: 'ALLOCATED',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: ['TABLE'],
          selected: false,
          rotation: 0,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 11,
            y: 2,
            z: 0,
          },
        },
        {
          number: '24',
          state: 'ALLOCATED',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: ['TABLE'],
          selected: false,
          rotation: 180,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 16,
            y: 2,
            z: 0,
          },
        },
        {
          number: '21',
          state: 'ALLOCATED',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: ['TABLE'],
          selected: false,
          rotation: 0,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 12,
            y: 8,
            z: 0,
          },
        },
        {
          number: '22',
          state: 'ALLOCATED',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: ['TABLE'],
          selected: false,
          rotation: 180,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 17,
            y: 8,
            z: 0,
          },
        },
        {
          number: '31',
          state: 'ALLOCATED',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: ['TABLE'],
          selected: false,
          rotation: 0,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 19,
            y: 8,
            z: 0,
          },
        },
        {
          number: '32',
          state: 'ALLOCATED',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: ['TABLE'],
          selected: false,
          rotation: 180,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 24,
            y: 8,
            z: 0,
          },
        },
        {
          number: '52',
          state: 'ALLOCATED',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 180,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 45,
            y: 8,
            z: 0,
          },
        },
        {
          number: '51',
          state: 'ALLOCATED',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 0,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 41,
            y: 8,
            z: 0,
          },
        },
        {
          number: '71',
          state: 'ALLOCATED',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 0,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 50,
            y: 7,
            z: 0,
          },
        },
        {
          number: '72',
          state: 'ALLOCATED',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 180,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 54,
            y: 8,
            z: 0,
          },
        },
        {
          number: '75',
          state: 'ALLOCATED',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 0,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 50,
            y: 1,
            z: 0,
          },
        },
        {
          number: '76',
          state: 'ALLOCATED',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 180,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 54,
            y: 0,
            z: 0,
          },
        },
      ],
      serviceElements: [
        {
          icon: 'WHEELCHAIR_ICON',
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 43,
            y: 2,
            z: 0,
          },
        },
      ],
      graphicElements: [
        {
          icon: 'ENTRY_EXIT',
          dimension: {
            w: 4,
            h: 1,
          },
          position: {
            x: 35,
            y: 0,
            z: 0,
          },
          rotation: 90,
        },
        {
          icon: 'LUGGAGE_AREA',
          dimension: {
            w: 3,
            h: 2,
          },
          position: {
            x: 8,
            y: 0,
            z: 0,
          },
          rotation: 0,
        },
        {
          icon: 'COMPARTMENT_PASSAGE_LOW',
          dimension: {
            w: 1,
            h: 10,
          },
          position: {
            x: 40,
            y: 0,
            z: 0,
          },
          rotation: 0,
        },
        {
          icon: 'TOILET_AREA',
          dimension: {
            w: 4,
            h: 3,
          },
          position: {
            x: 1,
            y: 0,
            z: 0,
          },
          rotation: 0,
        },
        {
          icon: 'TABLE',
          dimension: {
            w: 1,
            h: 2,
          },
          position: {
            x: 29,
            y: 8,
            z: 0,
          },
          rotation: 0,
        },
        {
          icon: 'TOILET_AREA',
          dimension: {
            w: 4,
            h: 3,
          },
          position: {
            x: 5,
            y: 7,
            z: 0,
          },
          rotation: 0,
        },
        {
          icon: 'TABLE',
          dimension: {
            w: 1,
            h: 4,
          },
          position: {
            x: 29,
            y: 0,
            z: 0,
          },
          rotation: 0,
        },
        {
          icon: 'TABLE',
          dimension: {
            w: 1,
            h: 2,
          },
          position: {
            x: 22,
            y: 8,
            z: 0,
          },
          rotation: 0,
        },
        {
          icon: 'ENTRY_EXIT',
          dimension: {
            w: 4,
            h: 1,
          },
          position: {
            x: 35,
            y: 9,
            z: 0,
          },
          rotation: 90,
        },
        {
          icon: 'TABLE',
          dimension: {
            w: 1,
            h: 4,
          },
          position: {
            x: 14,
            y: 0,
            z: 0,
          },
          rotation: 0,
        },
        {
          icon: 'COMPARTMENT_PASSAGE_LOW',
          dimension: {
            w: 1,
            h: 10,
          },
          position: {
            x: 33,
            y: 0,
            z: 0,
          },
          rotation: 0,
        },
        {
          icon: 'TABLE',
          dimension: {
            w: 1,
            h: 2,
          },
          position: {
            x: 15,
            y: 8,
            z: 0,
          },
          rotation: 0,
        },
        {
          icon: 'TABLE',
          dimension: {
            w: 1,
            h: 4,
          },
          position: {
            x: 22,
            y: 0,
            z: 0,
          },
          rotation: 0,
        },
        {
          icon: 'TOILET_AREA',
          dimension: {
            w: 4,
            h: 3,
          },
          position: {
            x: 1,
            y: 7,
            z: 0,
          },
          rotation: 0,
        },
        {
          icon: 'COACH_PASSAGE',
          dimension: {
            w: 1,
            h: 10,
          },
          position: {
            x: 56,
            y: 0,
            z: 0,
          },
          rotation: 180,
        },
        {
          icon: 'COACH_PASSAGE',
          dimension: {
            w: 1,
            h: 10,
          },
          position: {
            x: 0,
            y: 0,
            z: 0,
          },
          rotation: 0,
        },
      ],
      travelClass: ['FIRST'],
      propertyIds: ['WHEELCHAIR_ICON'],
    },
    {
      id: '0',
      number: 'At2(501)',
      dimension: {
        w: 28,
        h: 10,
      },
      places: [],
      serviceElements: [],
      graphicElements: [
        {
          icon: 'DRIVER_AREA_NO_VERTICAL_WALL',
          dimension: {
            w: 6,
            h: 10,
          },
          position: {
            x: 0,
            y: 0,
            z: 0,
          },
          rotation: 0,
        },
        {
          icon: 'DRIVER_AREA_NO_VERTICAL_WALL',
          dimension: {
            w: 6,
            h: 10,
          },
          position: {
            x: 22,
            y: 0,
            z: 0,
          },
          rotation: 180,
        },
      ],
      travelClass: ['FIRST'],
      propertyIds: [],
      type: 'LOCOMOTIVE_COACH'
    },
    {
      id: '9',
      number: 'A4(501)',
      dimension: {
        w: 57,
        h: 10,
      },
      places: [
        {
          number: '51',
          state: 'FREE',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 180,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 26,
            y: 8,
            z: 0,
          },
        },
        {
          number: '76',
          state: 'FREE',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 180,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 48,
            y: 0,
            z: 0,
          },
        },
        {
          number: '45',
          state: 'FREE',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 180,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 20,
            y: 0,
            z: 0,
          },
        },
        {
          number: '43',
          state: 'FREE',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 180,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 20,
            y: 2,
            z: 0,
          },
        },
        {
          number: '31',
          state: 'FREE',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 0,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 13,
            y: 8,
            z: 0,
          },
        },
        {
          number: '32',
          state: 'FREE',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 180,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 17,
            y: 8,
            z: 0,
          },
        },
        {
          number: '21',
          state: 'FREE',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 0,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 7,
            y: 8,
            z: 0,
          },
        },
        {
          number: '22',
          state: 'FREE',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 180,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 11,
            y: 8,
            z: 0,
          },
        },
        {
          number: '85',
          state: 'FREE',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 0,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 50,
            y: 1,
            z: 0,
          },
        },
        {
          number: '86',
          state: 'FREE',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 180,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 54,
            y: 0,
            z: 0,
          },
        },
        {
          number: '35',
          state: 'FREE',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 0,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 13,
            y: 0,
            z: 0,
          },
        },
        {
          number: '33',
          state: 'FREE',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 0,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 13,
            y: 2,
            z: 0,
          },
        },
        {
          number: '36',
          state: 'FREE',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 180,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 17,
            y: 0,
            z: 0,
          },
        },
        {
          number: '34',
          state: 'FREE',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 180,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 17,
            y: 2,
            z: 0,
          },
        },
        {
          number: '46',
          state: 'FREE',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 180,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 23,
            y: 0,
            z: 0,
          },
        },
        {
          number: '44',
          state: 'FREE',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 180,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 23,
            y: 2,
            z: 0,
          },
        },
        {
          number: '15',
          state: 'FREE',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 0,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 1,
            y: 0,
            z: 0,
          },
        },
        {
          number: '16',
          state: 'FREE',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 180,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 5,
            y: 1,
            z: 0,
          },
        },
        {
          number: '65',
          state: 'ALLOCATED',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 0,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 41,
            y: 0,
            z: 0,
          },
        },
        {
          number: '63',
          state: 'ALLOCATED',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 0,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 41,
            y: 2,
            z: 0,
          },
        },
        {
          number: '66',
          state: 'ALLOCATED',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 180,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 45,
            y: 0,
            z: 0,
          },
        },
        {
          number: '64',
          state: 'ALLOCATED',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 180,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 45,
            y: 2,
            z: 0,
          },
        },
        {
          number: '55',
          state: 'ALLOCATED',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 0,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 25,
            y: 0,
            z: 0,
          },
        },
        {
          number: '53',
          state: 'ALLOCATED',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 0,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 25,
            y: 2,
            z: 0,
          },
        },
        {
          number: '56',
          state: 'ALLOCATED',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 180,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 31,
            y: 0,
            z: 0,
          },
        },
        {
          number: '54',
          state: 'ALLOCATED',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 180,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 31,
            y: 2,
            z: 0,
          },
        },
        {
          number: '81',
          state: 'FREE',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 0,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 50,
            y: 7,
            z: 0,
          },
        },
        {
          number: '82',
          state: 'FREE',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 180,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 54,
            y: 8,
            z: 0,
          },
        },
        {
          number: '11',
          state: 'FREE',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 0,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 1,
            y: 8,
            z: 0,
          },
        },
        {
          number: '12',
          state: 'FREE',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 180,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 5,
            y: 7,
            z: 0,
          },
        },
        {
          number: '61',
          state: 'ALLOCATED',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 0,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 41,
            y: 8,
            z: 0,
          },
        },
        {
          number: '62',
          state: 'ALLOCATED',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 180,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 45,
            y: 8,
            z: 0,
          },
        },
        {
          number: '41',
          state: 'FREE',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 0,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 19,
            y: 8,
            z: 0,
          },
        },
        {
          number: '42',
          state: 'FREE',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 180,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 23,
            y: 8,
            z: 0,
          },
        },
        {
          number: '72',
          state: 'FREE',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 180,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 48,
            y: 8,
            z: 0,
          },
        },
        {
          number: '25',
          state: 'FREE',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 0,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 10,
            y: 0,
            z: 0,
          },
        },
        {
          number: '23',
          state: 'FREE',
          type: 'SEAT',
          travelClass: 'FIRST',
          remarkId: '',
          propertyIds: [],
          selected: false,
          rotation: 0,
          dimension: {
            w: 2,
            h: 2,
          },
          position: {
            x: 10,
            y: 2,
            z: 0,
          },
        },
      ],
      serviceElements: [],
      graphicElements: [
        {
          icon: 'COMPARTMENT_PASSAGE_LOW',
          dimension: {
            w: 1,
            h: 10,
          },
          position: {
            x: 33,
            y: 0,
            z: 0,
          },
          rotation: 0,
        },
        {
          icon: 'COMPARTMENT_PASSAGE_LOW',
          dimension: {
            w: 1,
            h: 10,
          },
          position: {
            x: 40,
            y: 0,
            z: 0,
          },
          rotation: 0,
        },
        {
          icon: 'ENTRY_EXIT',
          dimension: {
            w: 4,
            h: 1,
          },
          position: {
            x: 35,
            y: 0,
            z: 0,
          },
          rotation: 90,
        },
        {
          icon: 'LUGGAGE_AREA',
          dimension: {
            w: 4,
            h: 2,
          },
          position: {
            x: 28,
            y: 8,
            z: 0,
          },
          rotation: 0,
        },
        {
          icon: 'LUGGAGE_AREA',
          dimension: {
            w: 3,
            h: 2,
          },
          position: {
            x: 7,
            y: 0,
            z: 0,
          },
          rotation: 0,
        },
        {
          icon: 'COACH_PASSAGE',
          dimension: {
            w: 1,
            h: 10,
          },
          position: {
            x: 56,
            y: 0,
            z: 0,
          },
          rotation: 180,
        },
        {
          icon: 'ENTRY_EXIT',
          dimension: {
            w: 4,
            h: 1,
          },
          position: {
            x: 35,
            y: 9,
            z: 0,
          },
          rotation: 90,
        },
        {
          icon: 'COACH_PASSAGE',
          dimension: {
            w: 1,
            h: 10,
          },
          position: {
            x: 0,
            y: 0,
            z: 0,
          },
          rotation: 0,
        },
      ],
      travelClass: ['FIRST'],
      propertyIds: ['WHEELCHAIR_ICON', 'MULTI_FUNCTION_ICON'],
    },
  ],
};
