/**
 * This file is autogenerated by the event-sync plugin.
 * See stencil.config.ts in the root directory.
 */
export default {
  change: 'change',
  didChange: 'didChange',
  didClose: 'did-close',
  didOpen: 'did-open',
  input: 'input',
  stateChange: 'state-change',
  willClose: 'will-close',
  willOpen: 'will-open',
};
