/**
 * This file is autogenerated by the event-sync plugin.
 * See stencil.config.ts in the root directory.
 */
export default {
  didChange: 'didChange',
  sbbCheckboxLoaded: 'sbb-checkbox-loaded',
  stateChange: 'state-change',
};
