/**
 * This file is autogenerated by the event-sync plugin.
 * See stencil.config.ts in the root directory.
 */
export default {
  backClick: 'request-back-action',
  didClose: 'did-close',
  didOpen: 'did-open',
  willClose: 'will-close',
  willOpen: 'will-open',
};
