/**
 * This file is autogenerated by the event-sync plugin.
 * See stencil.config.ts in the root directory.
 */
export default {
  backClick: 'sbb-dialog_request-back-action',
  didDismiss: 'sbb-dialog_did-dismiss',
  didPresent: 'sbb-dialog_did-present',
  willDismiss: 'sbb-dialog_will-dismiss',
  willPresent: 'sbb-dialog_will-present',
};
