import { existsSync, globSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, join, relative } from 'node:path';

import { format, resolveConfig } from 'prettier';

const projectRoot = join(import.meta.dirname, '..');

function replaceGeneratedBlock(section: string, content: string, newContent: string): string {
  const blockName = `auto-generated-scss-module-${section}`;
  const start = `// start-${blockName}`;
  const end = `// end-${blockName}`;

  const regex = new RegExp(`(${start})[\\s\\S]*?(${end})`, 'g');

  return content.replace(regex, `$1\n${newContent}${newContent.length ? '\n' : ''}$2`);
}

function extractModuleName(file: string): string {
  return basename(file).replace(/^_/, '').split('.')[0];
}

async function generateScssApi(packagePath: string, files: string[]): Promise<void> {
  const forwards = [
    `// This file is auto-generated by ${relative(projectRoot, import.meta.filename)}`,
  ];

  // If there is a core Sass mixins API, add it first
  if (existsSync(join(packagePath, 'core/styles/_index.scss'))) {
    forwards.push("@forward './core/styles';");
  }

  for (const file of files) {
    const rel = relative(packagePath, file);
    // Convert to @forward path: remove leading _, remove .scss extension
    const forwardPath = `./${rel.replace(/\/_/g, '/').replace(/\.scss$/, '')}`;

    // Derive alias from file name
    const moduleName = extractModuleName(file);
    forwards.push(`@forward '${forwardPath}' as ${moduleName}-*;`);
  }

  const indexPath = join(packagePath, '_index.scss');

  // Write file and apply prettier to avoid formatting conflicts
  writeFileSync(
    indexPath,
    await format(forwards.join('\n'), {
      ...(await resolveConfig(indexPath)),
      filepath: indexPath,
    }),
    'utf8',
  );

  console.log(`Sass index file ${relative(projectRoot, indexPath)} has been generated.`);
}

async function generateTheme(
  packagePath: string,
  files: string[],
  includeDesignTokens: boolean,
): Promise<void> {
  const themePath = join(packagePath, 'core/styles/_theme.scss');
  const themeContent = readFileSync(themePath, 'utf-8');
  const globalFiles: {
    moduleName: string;
    relativePath: string;
    hasBase: boolean;
    hasForcedColors: boolean;
    hasBreakpointSmall: boolean;
    hasBreakpointLarge: boolean;
    hasBreakpointUltra: boolean;
    hasRules: boolean;
  }[] = [];

  if (includeDesignTokens) {
    globalFiles.push({
      moduleName: 'sbb-css-tokens',
      relativePath: '@sbb-esta/lyne-design-tokens/dist/scss/sbb-variables-as-css.scss',
      hasBase: true,
      hasForcedColors: true,
      hasBreakpointSmall: true,
      hasBreakpointLarge: true,
      hasBreakpointUltra: true,
      hasRules: false,
    });
  }

  globalFiles.push(
    ...files
      .map((file) => {
        // We have to create the relative path, clean "_" from file name and remove the .scss suffix
        const relativePath = relative(join(themePath, '..'), file.replace(/\/_/g, '/')).replace(
          /\.scss$/,
          '',
        );
        const moduleName = extractModuleName(file);

        const content = readFileSync(file, 'utf-8');

        return {
          moduleName,
          relativePath,
          hasBase: content.includes('@mixin base {'),
          hasForcedColors: content.includes('@mixin forced-colors {'),
          hasBreakpointSmall: content.includes('@mixin breakpoint-small {'),
          hasBreakpointLarge: content.includes('@mixin breakpoint-large {'),
          hasBreakpointUltra: content.includes('@mixin breakpoint-ultra {'),
          hasRules: content.includes('@mixin rules {'),
        };
      })
      .sort((a, b) => a.moduleName.localeCompare(b.moduleName)),
  );

  let newContent = themeContent;
  newContent = replaceGeneratedBlock(
    'imports',
    newContent,
    globalFiles
      .map((f) => `@use '${f.relativePath}' as ${f.moduleName} with ($theme: $theme);`)
      .join('\n'),
  );

  let rootBlock = globalFiles
    .filter((f) => f.hasBase)
    .map((f) => `@include ${f.moduleName}.base;`)
    .join('\n');

  const forcedColors = globalFiles.filter((f) => f.hasForcedColors);
  if (forcedColors.length) {
    rootBlock += `@media (forced-colors: active) {
      ${globalFiles
        .filter((f) => f.hasForcedColors)
        .map((f) => `@include ${f.moduleName}.forced-colors;`)
        .join('\n')}
    }`;
  }

  const breakpointSmall = globalFiles.filter((f) => f.hasBreakpointSmall);
  if (breakpointSmall.length) {
    rootBlock += `@include sbb.mq($from: small) {
      ${breakpointSmall.map((f) => `@include ${f.moduleName}.breakpoint-small;`).join('\n')}
    }`;
  }

  const breakpointLarge = globalFiles.filter((f) => f.hasBreakpointLarge);
  if (breakpointLarge.length) {
    rootBlock += `@include sbb.mq($from: large) {
      ${breakpointLarge.map((f) => `@include ${f.moduleName}.breakpoint-large;`).join('\n')}
    }`;
  }

  const breakpointUltra = globalFiles.filter((f) => f.hasBreakpointUltra);
  if (breakpointUltra.length) {
    rootBlock += `@include sbb.mq($from: ultra) {
      ${breakpointUltra.map((f) => `@include ${f.moduleName}.breakpoint-ultra;`).join('\n')}
    }`;
  }
  newContent = replaceGeneratedBlock('root', newContent, rootBlock);

  newContent = replaceGeneratedBlock(
    'rules',
    newContent,
    globalFiles
      .filter((f) => f.hasRules)
      .map((f) => `@include ${f.moduleName}.rules;`)
      .join('\n'),
  );

  // Write file and apply prettier to avoid formatting conflicts
  writeFileSync(
    themePath,
    await format(newContent, {
      ...(await resolveConfig(themePath)),
      filepath: themePath,
    }),
    'utf8',
  );

  console.log(`Theme file ${relative(projectRoot, themePath)} has been updated.`);
}

async function handleGlobalScssFiles(
  packagePath: string,
  includeDesignTokens: boolean,
): Promise<void> {
  const files = globSync('**/_*.global.scss', {
    cwd: packagePath,
    exclude: (p) => p.startsWith('core/styles/'),
  })
    .sort()
    .map((f) => join(packagePath, f));

  await generateScssApi(packagePath, files);
  await generateTheme(packagePath, files, includeDesignTokens);
}

await handleGlobalScssFiles(join(projectRoot, 'src/elements'), true);
await handleGlobalScssFiles(join(projectRoot, 'src/elements-experimental'), false);
