import { existsSync, globSync, writeFileSync } from 'node:fs';
import { basename, join, relative } from 'node:path';

import { format, resolveConfig } from 'prettier';

const projectRoot = join(import.meta.dirname, '..');

async function generateScssApi(packagePath: string): Promise<void> {
  const forwards = [
    `// This file is auto-generated by ${relative(projectRoot, import.meta.filename)}`,
  ];

  // If there is a core Sass mixins API, add it first
  if (existsSync(join(packagePath, 'core/styles/_index.scss'))) {
    forwards.push("@forward './core/styles';");
  }

  const files = globSync('**/_*.global.scss', {
    cwd: packagePath,
    exclude: (p) => p.startsWith('core/styles/'),
  })
    .sort()
    .map((f) => join(packagePath, f));

  for (const file of files) {
    const rel = relative(packagePath, file);
    // Convert to @forward path: remove leading _, remove .scss extension
    const forwardPath = `./${rel
      .replace(/\/_/g, '/')
      .replace(/^_/, '')
      .replace(/\.scss$/, '')}`;

    // Derive alias from file name
    const moduleName = basename(file).replace(/^_/, '').split('.')[0];
    forwards.push(`@forward '${forwardPath}' as ${moduleName}-*;`);
  }

  const indexPath = join(packagePath, '_index.scss');

  // Write file and apply prettier to avoid formatting conflicts
  writeFileSync(
    indexPath,
    await format(forwards.join('\n'), {
      ...(await resolveConfig(indexPath)),
      filepath: indexPath,
    }),
    'utf8',
  );

  console.log(`Sass index file ${relative(projectRoot, indexPath)} has been generated.`);
}

await generateScssApi(join(projectRoot, 'src/elements'));
await generateScssApi(join(projectRoot, 'src/elements-experimental'));
