import { existsSync, globSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, join, relative } from 'node:path';

import { format, resolveConfig } from 'prettier';

const projectRoot = join(import.meta.dirname, '..');

interface GlobalScssFile {
  filePath: string;
  moduleName: string;
  hasBase: boolean;
  hasForcedColors: boolean;
  hasBreakpointSmall: boolean;
  hasBreakpointLarge: boolean;
  hasBreakpointUltra: boolean;
  hasRules: boolean;
}

function replaceGeneratedBlock(section: string, content: string, newContent: string): string {
  const blockName = `auto-generated-scss-module-${section}`;
  const start = `// start-${blockName}`;
  const end = `// end-${blockName}`;

  if (!content.includes(start)) {
    throw new Error(`${start} marker not found`);
  }

  if (!content.includes(end)) {
    throw new Error(`${end} marker not found`);
  }

  const regex = new RegExp(`(${start})[\\s\\S]*?(${end})`, 'g');

  return content.replace(regex, `$1\n${newContent}\n\n$2`);
}

function normalizeScssFileName(fileName: string): string {
  return fileName.replace(/\/_/g, '/').replace(/\.scss$/, '');
}

async function generateScssApi(packagePath: string, globalFiles: GlobalScssFile[]): Promise<void> {
  const forwards = [
    `// This file is auto-generated by ${relative(projectRoot, import.meta.filename)}`,
  ];

  // If there is a core Sass mixins API, add it first
  if (existsSync(join(packagePath, 'core/styles/_index.scss'))) {
    forwards.push("@forward './core/styles';");
  }

  for (const { filePath, moduleName } of globalFiles) {
    forwards.push(
      `@forward './${normalizeScssFileName(relative(packagePath, filePath))}' as ${moduleName}-*;`,
    );
  }

  const indexPath = join(packagePath, '_index.scss');

  // Write file and apply prettier to avoid formatting conflicts
  writeFileSync(
    indexPath,
    await format(forwards.join('\n'), {
      ...(await resolveConfig(indexPath)),
      filepath: indexPath,
    }),
    'utf8',
  );

  console.log(`Sass index file ${relative(projectRoot, indexPath)} has been generated.`);
}

async function generateTheme(
  packagePath: string,
  globalFiles: GlobalScssFile[],
  includeDesignTokens: boolean,
): Promise<void> {
  const themePath = join(packagePath, 'core/styles/_theme.scss');
  const themeContent = readFileSync(themePath, 'utf-8');
  const themeFiles: GlobalScssFile[] = [
    ...(includeDesignTokens
      ? [
          {
            filePath: '@sbb-esta/lyne-design-tokens/dist/scss/sbb-variables-as-css.scss',
            moduleName: 'sbb-css-tokens',
            hasBase: true,
            hasForcedColors: true,
            hasBreakpointSmall: true,
            hasBreakpointLarge: true,
            hasBreakpointUltra: true,
            hasRules: false,
          },
        ]
      : []),
    ...globalFiles,
  ];

  let newThemeContent = themeContent;
  newThemeContent = replaceGeneratedBlock(
    'imports',
    newThemeContent,
    themeFiles
      .map(
        (f) =>
          `@use '${
            // node_modules imports shouldn't be transformed
            f.filePath.startsWith('@')
              ? f.filePath
              : relative(join(themePath, '..'), normalizeScssFileName(f.filePath))
          }' as ${f.moduleName} with ($theme: $theme);`,
      )
      .join('\n'),
  );

  let rootBlock = themeFiles
    .filter((f) => f.hasBase)
    .map((f) => `@include ${f.moduleName}.base;`)
    .join('\n');

  const forcedColors = themeFiles.filter((f) => f.hasForcedColors);
  if (forcedColors.length) {
    rootBlock += `@media (forced-colors: active) {
      ${forcedColors.map((f) => `@include ${f.moduleName}.forced-colors;`).join('\n')}
    }`;
  }

  for (const breakpoint of ['Small', 'Large', 'Ultra'] as const) {
    const matching = themeFiles.filter((f) => f[`hasBreakpoint${breakpoint}`]);
    if (matching.length) {
      rootBlock += `@include sbb.mq($from: ${breakpoint.toLowerCase()}) {
      ${matching.map((f) => `@include ${f.moduleName}.breakpoint-${breakpoint.toLowerCase()};`).join('\n')}    }`;
    }
  }
  newThemeContent = replaceGeneratedBlock('root', newThemeContent, rootBlock);

  newThemeContent = replaceGeneratedBlock(
    'rules',
    newThemeContent,
    themeFiles
      .filter((f) => f.hasRules)
      .map((f) => `@include ${f.moduleName}.rules;`)
      .join('\n'),
  );

  // Write file and apply prettier to avoid formatting conflicts
  writeFileSync(
    themePath,
    await format(newThemeContent, {
      ...(await resolveConfig(themePath)),
      filepath: themePath,
    }),
    'utf8',
  );

  console.log(`Theme file ${relative(projectRoot, themePath)} has been updated.`);
}

async function handleGlobalScssFiles(
  packagePath: string,
  includeDesignTokensInTheme: boolean,
): Promise<void> {
  const globalFiles = globSync('**/_*.global.scss', {
    cwd: packagePath,
    exclude: (p) => p.startsWith('core/styles/'),
  })
    .map((f) => {
      const filePath = join(packagePath, f);
      const moduleName = basename(filePath).replace(/^_/, '').split('.')[0];
      const content = readFileSync(filePath, 'utf-8');

      return {
        filePath,
        moduleName,
        hasBase: content.includes('@mixin base {'),
        hasForcedColors: content.includes('@mixin forced-colors {'),
        hasBreakpointSmall: content.includes('@mixin breakpoint-small {'),
        hasBreakpointLarge: content.includes('@mixin breakpoint-large {'),
        hasBreakpointUltra: content.includes('@mixin breakpoint-ultra {'),
        hasRules: content.includes('@mixin rules {'),
      };
    })
    .sort((a, b) => a.moduleName.localeCompare(b.moduleName));

  await generateScssApi(packagePath, globalFiles);
  await generateTheme(packagePath, globalFiles, includeDesignTokensInTheme);
}

await handleGlobalScssFiles(join(projectRoot, 'src/elements'), true);
await handleGlobalScssFiles(join(projectRoot, 'src/elements-experimental'), false);
