/**
 * This file is autogenerated by the event-sync plugin.
 * See stencil.config.ts in the root directory.
 */
export default {
  change: 'change',
  datePickerUpdated: 'datePickerUpdated',
  didChange: 'didChange',
  inputUpdated: 'inputUpdated',
  validationChange: 'validationChange',
};
