/**
 * This file is autogenerated by the event-sync plugin.
 * See stencil.config.ts in the root directory.
 */
export default {
  didDismiss: 'sbb-tooltip_did-dismiss',
  didPresent: 'sbb-tooltip_did-present',
  willDismiss: 'sbb-tooltip_will-dismiss',
  willPresent: 'sbb-tooltip_will-present',
};
