/**
 * This file is autogenerated by the event-sync plugin.
 * See stencil.config.ts in the root directory.
 */
export default {
  didClose: 'sbb-tooltip_did-close',
  didOpen: 'sbb-tooltip_did-open',
  willClose: 'sbb-tooltip_will-close',
  willOpen: 'sbb-tooltip_will-open',
};
