/**
 * This file is autogenerated by the event-sync plugin.
 * See stencil.config.ts in the root directory.
 */
export default {
  didPresent: 'did-present',
  dismissalRequested: 'dismissal-requested',
  willPresent: 'will-present',
};
