/**
 * This file is autogenerated by the event-sync plugin.
 * See stencil.config.ts in the root directory.
 */
export default {
  didPresent: 'sbb-alert_did-present',
  dismissalRequested: 'sbb-alert_dismissal-requested',
  willPresent: 'sbb-alert_will-present',
};
