name: mint
description: Setup https://github.com/mintoolkit/mint

runs:
  using: composite
  steps:
    - name: Create $HOME/.local/bin
      run: mkdir -p "$HOME/.local/bin"
      shell: bash
    - name: Cache mint
      id: cache-mint
      uses: actions/cache@v4
      with:
        path: /home/runner/.local/bin
        key: ${{ runner.os }}-mint
    - name: Setup mint
      if: steps.cache-mint.outputs.cache-hit != 'true'
      run: |
        mkdir -p "$HOME/.local/bin"
        cd "$HOME/.local/bin"

        # Get the current released tag_name
        VER=$(curl -sL https://api.github.com/repos/mintoolkit/mint/releases \
          | grep tag_name | head -n1 | cut -d'"' -f4)
        curl -L -o mint.tar.gz "https://github.com/mintoolkit/mint/releases/download/${VER}/dist_linux.tar.gz"
        tar -xvf mint.tar.gz --strip-components 1

        echo "Installed mint:${VER}"
      shell: bash
