/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  InterfaceHeadingAttributes,
} from './components/lyne-heading/lyne-heading.d';

export namespace Components {
  interface LyneCtaButton {
    /**
    * Id which is send in the click event payload
    */
    'eventId'?: string;
    /**
    * Label text to show on the button
    */
    'label': string;
    /**
    * @sampleDocTag sampleName - sampleValue
    * @sampleDocTag2 sampleName2 - sampleValue2
    */
    'samplePropForJSDocs': string;
  }
  interface LyneHeading {
    /**
    * Heading level
    */
    'level': InterfaceHeadingAttributes['level'];
    /**
    * Text for the Heading
    */
    'text': string;
    /**
    * Visual level for the heading
    */
    'visualLevel': InterfaceHeadingAttributes['visualLevel'];
  }
  interface LyneLink {
    /**
    * Link to use as href
    */
    'link': string;
    /**
    * If true, target=_blank will be set on the link
    */
    'openInNewWindow': boolean;
    /**
    * Text to show for the link
    */
    'text': string;
  }
}

declare global {


  interface HTMLLyneCtaButtonElement extends Components.LyneCtaButton, HTMLStencilElement {}
  var HTMLLyneCtaButtonElement: {
    prototype: HTMLLyneCtaButtonElement;
    new (): HTMLLyneCtaButtonElement;
  };

  interface HTMLLyneHeadingElement extends Components.LyneHeading, HTMLStencilElement {}
  var HTMLLyneHeadingElement: {
    prototype: HTMLLyneHeadingElement;
    new (): HTMLLyneHeadingElement;
  };

  interface HTMLLyneLinkElement extends Components.LyneLink, HTMLStencilElement {}
  var HTMLLyneLinkElement: {
    prototype: HTMLLyneLinkElement;
    new (): HTMLLyneLinkElement;
  };
  interface HTMLElementTagNameMap {
    'lyne-cta-button': HTMLLyneCtaButtonElement;
    'lyne-heading': HTMLLyneHeadingElement;
    'lyne-link': HTMLLyneLinkElement;
  }
}

declare namespace LocalJSX {
  interface LyneCtaButton {
    /**
    * Id which is send in the click event payload
    */
    'eventId'?: string;
    /**
    * Label text to show on the button
    */
    'label'?: string;
    /**
    * @sampleDocTag sampleName - sampleValue
    * @sampleDocTag2 sampleName2 - sampleValue2
    */
    'samplePropForJSDocs'?: string;
  }
  interface LyneHeading {
    /**
    * Heading level
    */
    'level'?: InterfaceHeadingAttributes['level'];
    /**
    * Text for the Heading
    */
    'text'?: string;
    /**
    * Visual level for the heading
    */
    'visualLevel'?: InterfaceHeadingAttributes['visualLevel'];
  }
  interface LyneLink {
    /**
    * Link to use as href
    */
    'link': string;
    /**
    * If true, target=_blank will be set on the link
    */
    'openInNewWindow'?: boolean;
    /**
    * Text to show for the link
    */
    'text': string;
  }

  interface IntrinsicElements {
    'lyne-cta-button': LyneCtaButton;
    'lyne-heading': LyneHeading;
    'lyne-link': LyneLink;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'lyne-cta-button': LocalJSX.LyneCtaButton & JSXBase.HTMLAttributes<HTMLLyneCtaButtonElement>;
      'lyne-heading': LocalJSX.LyneHeading & JSXBase.HTMLAttributes<HTMLLyneHeadingElement>;
      'lyne-link': LocalJSX.LyneLink & JSXBase.HTMLAttributes<HTMLLyneLinkElement>;
    }
  }
}


