name: Backport

on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  actions: write
  issues: write

jobs:
  backport:
    if: join(github.event.pull_request.labels) != '' &&
      github.event.pull_request.merged == true
    uses: sbb-design-systems/actions/.github/workflows/backport.yml@main
    secrets: inherit
