name: Build
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: read-all

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: yarn
      - run: yarn install --frozen-lockfile --non-interactive

      - name: Run linting
        run: yarn lint

  integrity:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: yarn
      - run: yarn install --frozen-lockfile --non-interactive

      - name: 'Integrity: Verify workspace integrity'
        run: yarn integrity
      - name: 'Integrity: Assert no changes (run `yarn integrity` if this fails)'
        run: git diff --exit-code

  build:
    runs-on: ubuntu-latest
    needs: lint
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: yarn
      - run: yarn install --frozen-lockfile --non-interactive
      - uses: actions/cache@v5
        with:
          path: node-modules/.cache
          key: build-cache-${{ hashFiles('**/*.ts') }}
          restore-keys: build-cache-

      - name: Run build
        run: yarn build
        env:
          VERSION: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Store PR number
        if: github.event_name == 'pull_request'
        run: echo "${{ github.event.number }}" > dist/docs/pr
      - name: Store docs artifacts
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v7
        with:
          name: docs
          path: dist/docs/
          retention-days: 1

      - name: Build and publish dev image
        uses: sbb-design-systems/actions/build-container@main
        if: github.ref == 'refs/heads/main'
        with:
          repository: docs
          tag: dev
