name: Release Please
on:
  push:
    branches:
      - '*.x'
      - main

# Documentation:
# https://github.com/googleapis/release-please
# https://github.com/googleapis/release-please-action
# https://github.com/googleapis/release-please/blob/main/docs/customizing.md

permissions:
  contents: write
  id-token: write # Required for OIDC
  packages: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub App token
        id: token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ secrets.BOT_ID }}
          private-key: ${{ secrets.BOT_PEM }}

      - name: Release Please
        uses: sbb-design-systems/actions/release-please@main
        with:
          app-token: ${{ steps.token.outputs.token }}
          teams-webhook: ${{ secrets.TEAMS_WEBHOOK }}
          dev-packages: true
