name: Visual Regression Secure
# Secure execution of continuous integration jobs
# which are performed upon completion of the
# "Continuous Integration" workflow
# https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
on:
  workflow_run:
    workflows: [Visual Regression]
    types: [completed]

env:
  VISUAL_REQUIRED: 'pr: visual review required'
  VISUAL_APPROVED: 'pr: visual review approved'

jobs:
  visual-regression:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    permissions:
      checks: write
      deployments: write
      packages: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: yarn
      - run: yarn install --frozen-lockfile --non-interactive

      - name: Create GitHub App token
        id: token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ secrets.BOT_ID }}
          private-key: ${{ secrets.BOT_PEM }}
      - uses: actions/download-artifact@v8
        with:
          name: visual-regression-screenshots
          path: dist/screenshots/
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ steps.token.outputs.token }}

      - name: Build visual-regression-app
        run: yarn build visual-regression-app

      - name: Read Pull Request Number
        id: pr-number
        run: echo "result=$(cat dist/screenshots/pr)" >> "$GITHUB_OUTPUT"

      - name: "Remove 'diff-available' label"
        # This label is used for filtering deployments in ArgoCD.
        # At the start of the workflow, we remove the container available labels
        # which will be re-added after the Secure workflow.
        run: gh issue edit $PR_NUMBER --repo ${{ github.repository }} --remove-label "diff-available"
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ steps.pr-number.outputs.result }}

      - name: Create check if changed
        uses: actions/github-script@v9
        id: screenshot-check
        env:
          urlTemplate: https://lyne-components-visual-regression-diff-pr{}.app.sbb.ch
          PR_NUMBER: ${{ steps.pr-number.outputs.result }}
        with:
          script: |
            const { readdirSync, readFileSync } = await import('fs');
            const diffUrl = process.env.urlTemplate.replace('{}', process.env.PR_NUMBER);
            const diffInfo = JSON.parse(readFileSync('dist/visual-regression-app/diff.json', 'utf8'));
            const createCheck = async (success) => {
              await github.rest.checks.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: 'Visual Regression Result',
                head_sha: context.payload.workflow_run.head_sha,
                details_url: diffUrl,
                output: {
                  title: `Visual Regression ${success ? 'Success' : `Failed (${diffInfo.changedAmount + diffInfo.newAmount})`}`,
                  summary: diffUrl,
                  text: `Changes: ${diffInfo.changedAmount}\nNew: ${diffInfo.newAmount}`,
                },
                ...(success ? { status: 'completed', conclusion: 'success' } : { status: 'in_progress' }),
              });

              const environment = `pr${process.env.PR_NUMBER}-diff`;
              const payload = { owner: context.repo.owner, repo: context.repo.repo, environment };
              const { data: deployment } = await github.rest.repos.createDeployment({
                ...payload,
                ref: context.payload.workflow_run.head_sha,
                auto_merge: false,
                required_contexts: ['finalize']
              });
              await github.rest.repos.createDeploymentStatus({
                ...payload,
                deployment_id: deployment.id,
                state: success ? 'inactive' : 'in_progress',
                environment_url: diffUrl,
              });
            };

            // If we have no screenshots, we do not need to create a check.
            if (readdirSync('dist/screenshots').length <= 1) {
              await createCheck(true);
              return 'empty';
            }

            let previousDiffInfo = {};
            try {
              const response = await fetch(diffUrl + 'diff.json');
              if (response.ok) {
                previousDiffInfo = await response.json();
              }
            } catch {}

            await createCheck(false);

            // If the diff hash is the same as previously, we do not need to update the state or containers.
            return diffInfo.hash === previousDiffInfo.hash ? 'no-change' : 'changed';
          result-encoding: string

      - name: Remove labels when no failed screenshots exist
        if: steps.screenshot-check.outputs.result == 'empty'
        run: gh issue edit $PR_NUMBER --remove-label "$VISUAL_REQUIRED"
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ steps.pr-number.outputs.result }}

      - name: Create visual regression container
        uses: sbb-design-systems/actions/build-container@main
        with:
          repository: visual-regression
          tag: pr${{ steps.pr-number.outputs.result }}
          containerfile: tools/visual-regression-testing/Containerfile

      - name: Apply labels
        if: steps.screenshot-check.outputs.result == 'changed' || steps.screenshot-check.outputs.result == 'empty'
        run: |
          gh issue edit $PR_NUMBER --remove-label "$VISUAL_APPROVED"
          gh issue edit $PR_NUMBER --add-label "$VISUAL_REQUIRED"
          gh issue edit $PR_NUMBER --add-label "diff-available"
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ steps.pr-number.outputs.result }}
